-- ERP/PQ sync v1.1 integration fields.
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'ELABORATO_PLANIMETRICO';

ALTER TABLE "FeasibilityStudy"
  ADD COLUMN IF NOT EXISTS "companyErpId" TEXT,
  ADD COLUMN IF NOT EXISTS "erpImportedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "erpUpdatedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "sourceSyncId" TEXT;

ALTER TABLE "PropertyDocument"
  ADD COLUMN IF NOT EXISTS "erpDocumentId" TEXT,
  ADD COLUMN IF NOT EXISTS "sha256" TEXT,
  ADD COLUMN IF NOT EXISTS "sizeBytes" INTEGER;
